name: Deploy Dev
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: >-
          docker login -u ${{secrets.DOCKERHUB_USER_NAME}} -p
          ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build Docker Image
        run: >-
          docker build -t maheshyadav7702/next-nest
          ../container/Dockerfile.client.prod
      - name: Publish  Image to docker hub
        run: 'docker push maheshyadav7702/next-nest:latest'
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: 'docker pull maheshyadav7702/next-nest:latest'
      - name: Run Docker Container
        run: >-
          docker run -d -p 3000:3000 --name next-app-container -e
          MONGO_PASSWORD='${{secrets.MONGO_PASSWORD}}' maheshyadav7702/next-nest
